#!/usr/bin/env bash
#
# scripts/stripe-setup.sh
#
# Creates Stripe test-mode products and prices for local development.
# Outputs environment variable exports to stdout; redirect to .env or source directly.
#
# Prerequisites:
#   - Stripe CLI installed and authenticated (`stripe login`)
#
# Usage:
#   ./scripts/stripe-setup.sh          # prints export commands
#   ./scripts/stripe-setup.sh >> .env  # appends to .env file
#
set -euo pipefail

command -v stripe >/dev/null 2>&1 || {
    echo "Error: stripe CLI not found. Install from https://stripe.com/docs/stripe-cli" >&2
    exit 1
}

echo "# Creating Stripe products and prices for local development..." >&2

# Create Premium product
PREMIUM_PROD=$(stripe products create \
    --name="Year of Bingo Premium" \
    --description="Premium subscription for Year of Bingo" \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

echo "# Created product: $PREMIUM_PROD" >&2

# Create monthly price ($4.99/month)
PRICE_MONTHLY=$(stripe prices create \
    --product="$PREMIUM_PROD" \
    --unit-amount=499 \
    --currency=usd \
    -d 'recurring[interval]=month' \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

echo "# Created monthly price: $PRICE_MONTHLY" >&2

# Create yearly price ($49.99/year)
PRICE_YEARLY=$(stripe prices create \
    --product="$PREMIUM_PROD" \
    --unit-amount=4999 \
    --currency=usd \
    -d 'recurring[interval]=year' \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

echo "# Created yearly price: $PRICE_YEARLY" >&2

# Create Lifetime product
LIFETIME_PROD=$(stripe products create \
    --name="Year of Bingo Premium Lifetime" \
    --description="One-time lifetime premium access" \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

echo "# Created lifetime product: $LIFETIME_PROD" >&2

# Create lifetime price ($99.99 one-time)
PRICE_LIFETIME=$(stripe prices create \
    --product="$LIFETIME_PROD" \
    --unit-amount=9999 \
    --currency=usd \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

echo "# Created lifetime price: $PRICE_LIFETIME" >&2

# Create Tip product
TIP_PROD=$(stripe products create \
    --name="Tip" \
    --description="Support Year of Bingo" \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

echo "# Created tip product: $TIP_PROD" >&2

# Create tip prices
PRICE_TIP_5=$(stripe prices create \
    --product="$TIP_PROD" \
    --unit-amount=500 \
    --currency=usd \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

PRICE_TIP_10=$(stripe prices create \
    --product="$TIP_PROD" \
    --unit-amount=1000 \
    --currency=usd \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

PRICE_TIP_20=$(stripe prices create \
    --product="$TIP_PROD" \
    --unit-amount=2000 \
    --currency=usd \
    2>/dev/null | grep '"id":' | head -1 | sed 's/.*"id": "\([^"]*\)".*/\1/')

echo "# Created tip prices: $PRICE_TIP_5, $PRICE_TIP_10, $PRICE_TIP_20" >&2

# Output environment variables
cat <<EOF

# Stripe price IDs (generated by scripts/stripe-setup.sh)
STRIPE_PREMIUM_PRICE_MONTHLY=$PRICE_MONTHLY
STRIPE_PREMIUM_PRICE_YEARLY=$PRICE_YEARLY
STRIPE_PREMIUM_PRICE_LIFETIME=$PRICE_LIFETIME
STRIPE_TIP_PRICE_5=$PRICE_TIP_5
STRIPE_TIP_PRICE_10=$PRICE_TIP_10
STRIPE_TIP_PRICE_20=$PRICE_TIP_20
EOF

echo "" >&2
echo "# Done! Add the above to your .env file or export them in your shell." >&2
